server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://185.2.168.15:3306/pelajar1_user_db
    password: 4r6i3;XIUJ+2ji
    username: pelajar1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect